### ISSUE TITLE
[Feature Request]: Allow passing custom serialized BUILD_INFO data at runtime

### ISSUE THREAD

**Issue by lexi-the-cute** [danielschemmel/build-info#25] opened 2024-11-26 04:41 UTC
There should be a way to override the saved build info with other build info. I'm trying to re-export the build-info for my proc macro crate so I can track the dependencies in that crate.

Something like the below code. The below code is untested.

```rust
#[cfg(feature = "runtime")]
#[proc_macro_error]
#[proc_macro]
pub fn custom_build_info(input: TokenStream, build_info_environment: Result<String, VarError>) -> TokenStream {
	function::build_info(input, deserialize_build_info(build_info_environment))
}
```

That way, I can pass in the environment from the macros crate to build info at runtime and get the build info for the macros crate from outside of the crate. The below code was tested with `println!("{}", #build_info)`

```rust
/// Generates `macros_build_info`
#[proc_macro]
pub fn macros_build_info(_: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let build_info: &str = env!("BUILD_INFO");
    quote::quote!{
        /// Build info for crate
        pub fn macros_build_info() {  //  -> build_info::BuildInfo
            build_info::proc::custom_build_info(
                #build_info
            );
        }
    }.into()
}
```

I would generate the `macros_build_info()` function with the below code outside of the function:

```rust
macros::macros_build_info!();
```

Then I would call the function like below:

```rust
macros_build_info();
```

**Comment by danielschemmel** [comment] 2024-11-26 14:50
Could you please elaborate why [`build_info::build_info!(pub fn build_info)`](https://docs.rs/build-info/latest/build_info/macro.build_info.html) does not suffice for your use case?

For normal crates that should already do the trick, but for a proc-macro crate there is of course the additional step of transmitting information from your proc-macro to the program, but that feels somewhat out of scope for this crate. Is there something that would make this step easier which build-info could provide?

**Comment by lexi-the-cute** [comment] 2024-11-29 20:08
A step that would make this easier would be adding a way to pass in custom build data at runtime so I can borrow your crate's parser instead of having to write my own. I can then handle the storage of the build string myself. I just have no way of being able to pass custom objects between the crates outside of what I can pass as a TokenStream

**Comment by lexi-the-cute** [comment] 2024-11-30 01:48
Looking more into this, as far as I can tell, neither build dependencies nor regular dependencies are embedded into the binary from proc macro crates, so this request may be moot if the dependencies aren't in the output binary to begin with

**Comment by danielschemmel** [comment] 2024-11-30 01:57
> Looking more into this, as far as I can tell, neither build dependencies nor regular dependencies are embedded into the binary from proc macro crates, [...]

That is correct. A proc-macro crate is basically a compiler plugin. Its normal dependencies are used at compile time (i.e., the runtime of the compiler plugin) and do not end up in the binary. Build dependencies never end up in the compiled binary.

> [...] a way to pass in custom build data at runtime so I can borrow your crate's parser [...]

By design, build-info does not process any data at runtime. Both the `build_info::format!` and `build_info::build_info!` macros generate their results at compile time. However, when the runtime is enabled, the build info types used by `build_info::build_info!` (e.g., [`build_info::BuildInfo`](https://docs.rs/build-info/latest/build_info/struct.BuildInfo.html)) have support for serde, so you could easily generate them using serialized data.

**Closed as completed** 2024-11-30 02:04 UTC
